### ISSUE TITLE
Scripts/Quests: player's phase does not change when accepting quest 'Something's Amiss'

### ISSUE THREAD

**Issue by webiummedia** [TrinityCore/TrinityCore#11201]
I have a problem at the worgen start location. The quest chain breaks at the second quest called "Something's Amiss". Prince Liam Greymane does not allow the quest to be turned in.
##

**Comment by ByteriderAT** [comment]
Hello there,
how can people help to fix this?
Is there a logic how the area could be fixed?
Are only Database entry's left? (So I could help I think)

**Comment by msoky** [comment]
at first, phases branch must be finished...phases is problem

**Comment by ByteriderAT** [comment]
Ok @msoky   Thank you, I thougt it has been fixed since the PR is merged. 
Thank you for the answer. :)

**Comment by gpn39f** [comment]
maybe it's a good Idee, first to make a tutorial how phases should work. 
and point all classes, where phases are involved..
i think mostly devs have no idee how this should work 
maybe are some note importent to: why are the work on the phase system being stopped

**Comment by dansanti** [comment]
Hi!, this bug still in 6.x.. can't select Prince Liam

**Comment by GnaXi** [comment]
Maybe move this to the 6.x branch, as it is still an issue? :)

**Comment by msoky** [comment]
any news about worgen starting location?

**Comment by nubqt** [comment]
Looked into `creatures` and the NPCs for phase 2 are missing (at least the Prince is as he has a different ID when for this quest: 34913). The relation between the quest and its ender is also missing in `gameobject_questender`.

I think a sniff could provide more info about all the NPCs. Then once we have that we just need to create a `smart_scripts` that increments the Player's phase to phase 2 so that he can see all the NPCs belonging to that spawnMask as defined in `creatures`.

Hope this helps!

#ps: can we please rename this ticket to 'Accepting quest 'Something's Amiss' does not change the player's phase'.

**Comment by Killyana** [comment]
@Ovahlord you already scripted this part I think.

**Comment by Ovahlord** [comment]
Dunno if this is on master. I surely did that on 434 with scripting the first quests but I don't know if the spawning sql contained that stuff already.

**Comment by SeluneArkadia** [comment]
Is there any explanation about the way to fix it (even manualy with SQL phpmyadmin or admin commands...) ?

**Comment by Killyana** [comment]
This zone is not scripted yet https://github.com/TrinityCore/TrinityCore/issues/15182
