### ISSUE TITLE
LFG issues

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#14331]
- [ ] enter a lfg dungeon, 1 leaves, queue inside the dungeon, 1 leaves: can't queue anymore to continue
- [ ] enter a lfg dungeon, 1 leaves, try to kick another, 1 agrees, 1 denies: vote doesn't end but waits till it expires

**Comment by Gooyeth** [comment]
* Leave LFG group if player is out of dungeon and is only a player in group.

**Comment by ccrs** [comment]
* Luck of the Draw (http://www.wowhead.com/spell=72221) is given to all players in group

**Comment by Nyeriah** [comment]
* Dungeon Deserter not giving Deserter if players log out (players not being saved properly in general if they leave a RDF group)

https://github.com/TrinityCore/TrinityCore/issues/6824

**Comment by ccrs** [comment]
@Nyeriah Its kinda weird: sometimes it works, but sometimes it doesnt.
For heroic mode, it occasionally works but never for normal mode.

**Comment by Nyeriah** [comment]
As I explained in the issue, it only happens if they're inside an instance and thus being teleported by the time they're removed

**Comment by Nyeriah** [comment]
As I explained in the issue, it only happens if they're inside an instance and thus being teleported by the time they're removed

**Comment by Frytiks** [comment]
Player still reporting problem, there is still last missing player @jackpoz

**Comment by jackpoz** [comment]
@Frytiks : as asked quite a few times, post the lfg log set to "debug" level, anything else is useless

**Comment by Frytiks** [comment]
@jackpoz log with 55 minutes uptime. https://onedrive.live.com/redir?resid=41FEF50A040FE1C4!267&authkey=!APu97XTD6b6QUTw&ithint=file%2ctxt

**Comment by Frytiks** [comment]
https://onedrive.live.com/redir?resid=41FEF50A040FE1C4!268&authkey=!AEvwyhiXC_CyIfM&ithint=file%2clog next log

**Comment by Frytiks** [comment]
nvm, last player missing solved.

**Comment by Aokromes** [comment]
- [ ] before lfg queue debug used to show details of people on queue, now no.
- [ ] sugestion change [19:04:22] (1|2|3|4): Compatibles (Not enough players) into
                                   [19:04:22] (1 dps/tank|2 dps/heal|3 heal|4 dps): Compatibles (Not enough players) into
- [ ] complete one instance, remove most of members on party from it queue again, close client with X, queue with another member it will show the offline members has available on queue.

**Comment by Frytiks** [comment]
what does it mean in logs2015-04-11_00:04:29 Guids: (2256303413312619923|2256303413312620559) Too much players (6)

**Comment by Spp-** [comment]
As you don't log the logger name you don't figure where that comes from but still sound pretty clear to me. That message appears in debug mode while trying to match 2 groups, but total player count of both groups exceeds 5

**Comment by Frytiks** [comment]
I'm getting all day messages for some players queqing normally, but some are still in queue forever > 1 hour in queue and not matched group

**Comment by Frytiks** [comment]
@jackpoz Without Double Side group on server, queue works normally, there is problem when u have mixed groups, it's not joining correctly

**Comment by jackpoz** [comment]
is that "Double Side group" a feature enabled through worldserver.conf ?

**Comment by ccrs** [comment]
i have never enabled it, but:

````quote
#
#    AllowTwoSide.Interaction.Group
#        Description: Allow group joining between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Group = 0
````

**Comment by Frytiks** [comment]
Ye i think that @ccrs  !

**Comment by w1sht0l1v3** [comment]
Join lfg with a group.Now have the members close wow(not logout,press X on the game window..like a dc) the group will remain in queue..even if the members are offline.

If a player joins lfg queue,then alt+f4 the game,he remains in queue,but on next join from other player/group it gets removed..so this is ok more or less...

Now..can we atleast port this kind of behaviour to groups also?As in if a member of a queued group is offline,remove the whole group from queue.This bug breaks lfg queue system very fast.

**Comment by Frytiks** [comment]
Any news about this. I try what you say and Yes, it's bugging queue. Maybe we can remove groups with 0 players in FindGroups() function ? @jackpoz

**Comment by Nyeriah** [comment]
Offline players don't get removed from the queue. At least, not at 6.x. There's a delay before they're removed after being logged off (just leaving this as a note for @w1sht0l1v3 )

**Comment by Frytiks** [comment]
When i restart server queue works good like 2 hours, but after 2 hours it's not queue, all is in log what i posted upside. Like @w1sht0l1v3 say, it causing bug.

**Comment by Voidx** [comment]
as @Frytiks says every 2 o 3 hours lfg freeze.

**Comment by Frytiks** [comment]
I can post debug log again, but jackpoz not trust me

**Comment by Frytiks** [comment]
@jackpoz Summoning, i have 1GB of LFG.log should i upload it ?

**Comment by Frytiks** [comment]
@jackpoz here is log https://mega.nz/#!yh5E2SZK!RGVAA1GgHhIt3KiPC9xinaESIl9yVN_xFUdS2BggtRs

**Comment by Aokromes** [comment]
You don't know rar you dont?

**Comment by Frytiks** [comment]
Hard to me

**Comment by Frytiks** [comment]
@Aokromes Like you want, in zip, link: https://mega.nz/#!ylpVzTpa!sQujKqSfCgUz44Q6SK_va1dN5NEPEXakSvaVCitFDAc

**Comment by Voidx** [comment]
Any news about it?

**Comment by Aokromes** [comment]
BTW. on retail when you queue into LFG and  you are teleported to one already existing instance you are teleported to any random member of the group.

**Comment by jackpoz** [comment]
> Luck of the Draw (http://www.wowhead.com/spell=72221) is given to all players in group

@ccrs please state the current behavior and the correct behavior so one doesn't have to wonder about what to fix

**Comment by jackpoz** [comment]
- [ ] not all matches are checked, leading to stuck queue. Notice how (79|2256303413312618500) is missing below

>TC> lfg queue debug
Number of Queues: 1
Queued Players: 2 (in group: 4) Groups: 1
Compatible Map size: 6
(18): Compatibles (Not enough players)
(18|2256303413312618500): Incompatible dungeons
(18|79): Compatibles (Not enough players)
(18|79|2256303413312618500): Incompatible dungeons
(2256303413312618500): Compatibles (Not enough players)
(79): Compatibles (Not enough players)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b7f9836d223925802115f45ad2c2c7eeb9bb00a4 fixed quite some issues, please check if it improves lfg queue

**Comment by Frytiks** [comment]
Not enough players to test

**Comment by jackpoz** [comment]
- [ ] apply https://github.com/TrinityCore/TrinityCore/commit/1e71aba2ee656a8407dec63a69d0879e16a070e2 to "lfg queue debug"

**Comment by Voidx** [comment]
lfg estop work every 30 min aprox.

**Comment by Voidx** [comment]
lfg guid was on some cases incorrect, example:
2015-10-26_03:32:19 [lfg.queue.match.compatibility.check] Guids: (167855|339518|369242|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:19 [lfg.queue.match.compatibility.check] Guids: (136300|167855|369242|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:19 [lfg.queue.match.compatibility.check] Guids: (167855|369242|385616|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:19 [lfg.queue.match.compatibility.check] Guids: (167855|2256303413312622541|2256303413312624458) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|406136|406166|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|319936|406136|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|2256303413312622541|2256303413312624688) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|339518|406136|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (136300|167855|406136|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|385616|406136|2256303413312622541) Group MATCH but can't create proposal!
2015-10-26_03:32:34 [lfg.queue.match.compatibility.check] Guids: (167855|2256303413312622541|2256303413312624458) Group MATCH but can't create proposal!
2015-10-26_03:42:56 [lfg.queue.match.compatibility.check] Guids: (201236|214834|257640|302470|407524) MATCH! Group formed
2015-10-26_03:43:10 [lfg.queue.match.compatibility.check] Guids: (113432|356717|398091|2256303413312618658) MATCH! Group formed
2015-10-26_03:45:38 [lfg.queue.match.compatibility.check] Guids: (52722|118828|335274|401785|411757) MATCH! Group formed
2015-10-26_03:45:53 [lfg.queue.match.compatibility.check] Guids: (1246|99950|2256303413312618714) MATCH! Group formed
2015-10-26_03:46:33 [lfg.queue.match.compatibility.check] Guids: (68554|141187|368117|376511|390970) MATCH! Group formed
2015-10-26_03:47:19 [lfg.queue.match.compatibility.check] Guids: (127536|153661|359642|375721|376511) MATCH! Group formed
2015-10-26_03:47:49 [lfg.queue.match.compatibility.check] Guids: (136300|249895|319936|394920|398914) MATCH! Group formed
2015-10-26_03:48:02 [lfg.queue.match.compatibility.check] Guids: (337859|390970|405595|2256303413312619121) MATCH! Group formed
2015-10-26_03:48:05 [lfg.queue.match.compatibility.check] Guids: (40360|153661|376511|406029|419377) MATCH! Group formed
2015-10-26_03:48:12 [lfg.queue.match.compatibility.check] Guids: (11713|30274|422612|2256303413312619155) MATCH! Group formed
2015-10-26_03:48:51 [lfg.queue.match.compatibility.check] Guids: (108595|368117|376511|385769|390970) MATCH! Group formed
2015-10-26_03:48:58 [lfg.queue.match.compatibility.check] Guids: (43410|238493|407776|2256303413312619155) MATCH! Group formed
2015-10-26_03:48:59 [lfg.queue.match.compatibility.check] Guids: (91049|131192|160044|418472|423055) MATCH! Group formed
2015-10-26_03:49:00 [lfg.queue.match.compatibility.check] Guids: (127536|153661|337859|390937|405595) MATCH! Group formed
2015-10-26_03:49:31 [lfg.queue.match.compatibility.check] Guids: (2256303413312619163) MATCH! Group formed
2015-10-26_03:49:34 [lfg.queue.match.compatibility.check] Guids: (11713|414155|422612|2256303413312619130) MATCH! Group formed


I have guids like 2256303413312619130 but no one player has dat guid.

**Comment by tkrokli** [comment]
@Voidx : If you put ``` on a blank line before and after your list, it will be easier to read and compare. :)

**Comment by Aokromes** [comment]
2256303413312619130  is group. it's perfect valid.

**Comment by Spp-** [comment]
Apply this patch and enable lfg.allqueued DEBUG log. It will give more detailed info.
```
diff --git a/src/server/game/DungeonFinding/LFGMgr.cpp b/src/server/game/DungeonFinding/LFGMgr.cpp
index 250f6e0..b5e1ffe 100644
--- a/src/server/game/DungeonFinding/LFGMgr.cpp
+++ b/src/server/game/DungeonFinding/LFGMgr.cpp
@@ -1900,8 +1900,16 @@ bool LFGMgr::AllQueued(GuidList const& check)
         return false;
 
     for (GuidList::const_iterator it = check.begin(); it != check.end(); ++it)
-        if (GetState(*it) != LFG_STATE_QUEUED)
-            return false;
+    {
+        LfgState state = GetState(*it);
+        if (state != LFG_STATE_QUEUED)
+        {
+            if (state != LFG_STATE_PROPOSAL)
+                TC_LOG_DEBUG("lfg.allqueued", "Unexpected state found while trying to form new group. Guid: %s, State: %s", guid.ToString().c_str(), GetStateString(state).c_str());
+
+            return false
+        }
+    }
     return true;
 }

**Comment by Voidx** [comment]
http://pastebin.com/N9wNCZUW So much Unexpected state found.

**Comment by Rushor** [comment]
> implement whatever cooldown there should be between vote kicks, it's just a time(NULL) check

since patch 3.3.3 the cooldown should NO longer be displayed as debuff http://www.wowhead.com/spell=71328/dungeon-cooldown.

source:
http://wowwiki.wikia.com/wiki/Patch_3.3.3
The Random Dungeon cooldown is no longer displayed as a debuff. Instead, players will see the cooldown time remaining displayed in the Dungeon Finder window when Random Dungeon or Random Heroic Dungeon is selected from the pull-down. 

currently:
i'm not shure if this timer display is already implemented. maybe it needs some upates for the worldstate like the timer for wintergrasp.
However tc is curently on version <3.3.3 because we are still using the cooldown:
https://github.com/TrinityCore/TrinityCore/blob/478cc756eb05591f36857be3ffd1895684529710/src/server/game/DungeonFinding/LFGMgr.cpp#L429

**Comment by Rushor** [comment]
- [ ] [Archievement] Looking For Many https://github.com/TrinityCore/TrinityCore/issues/12187 (priority cosmetic)

**Comment by Rushor** [comment]
kay i updated this mainticket a bit to get a better overview, corrently i cannot find more issues to it

**Comment by Saben65** [comment]
I have no way to test it for certain, but a few months ago I was playing on a TC 3.3.5 server and one issue that appeared somewhat regularly was seemingly losing your place in the queue. It happened under the following circumstances.

1. Join queue, wait for tank
2. Tank joins, wait for everyone to accept
3. One member (not the tank) misses/doesn't accept the queue.
4. Tank gets put into the next group in the queue, you are thrown back into the queue and have to wait for a new tank.

I believe it should keep the tank in your group, and try to find a dps or healer as a replacement. If the tank was put into your group, I am pretty sure that meant you were at the top of the list (server had very few tanks queueing). It seems what was happening was you would lose your place in queue after a player misses the queue, regardless if you queued together or not.

Once again, this was a few months ago, and I do not know how I could test this without running numerous instances of the game.

**Comment by jackpoz** [comment]
> I do not know how I could test this without running numerous instances of the game.

what's the problem with running numerous instances of the game ?

**Comment by Rushor** [comment]
> It seems what was happening was you would lose your place in queue after a player misses the queue, regardless if you queued together or not.

if someone does not accept the queue your are thrown back to the last place of the queue. normally everyone should be in the first place of the queue again, that's why you need to wait so long currently

**Comment by Saben65** [comment]
@rushor so you agree that if what I said is true, it is currently not functioning, correct?.

The reason I can't do multiple instances of the game is because I am on holiday and only have my netbook. Once I get back this weekend I will test it out and report back how it appears to be functioning.

**Comment by Rushor** [comment]
added https://github.com/TrinityCore/TrinityCore/issues/14705 to the list

**Comment by silvermcd123** [comment]
Check this 
http://s26.postimg.org/tm31tzu15/Wo_WScrn_Shot_050216_113514.jpg
on branch 3.3.5

**Comment by Rushor** [comment]
> queued as a healer and healer missing

maybe because of https://github.com/TrinityCore/TrinityCore/issues/16241 ?

**Comment by silvermcd123** [comment]
No. I blocked multiple roles on você.

**Comment by silvermcd123** [comment]
Code*

**Comment by silvermcd123** [comment]
btw guys, how to enable logs for LFG? been looking for that...

**Comment by silvermcd123** [comment]
Guys, pls test this.

- Join dungeon finder with any role for 5 mins
- Relog
- Join again and you will see that you queue time is 5 mins

something is wrong with that, dungeon finder data is not being cleared at logout???

**Comment by jackpoz** [comment]
> No. I blocked multiple roles on code.

I have no idea what custom changes you applied

**Comment by silvermcd123** [comment]
@jackpoz you tested what i said? No costum changes were made on that test. I just blocked multiple roles before to check if they were the cause, then i removed it. I'm using clean TC core.

**Comment by Frytiks** [comment]
@Jackpoz i have clean core and i can confirm that too, also this bug is on every server.

**Comment by silvermcd123** [comment]
i can even click on "find group" without choosing any roles because it has already my roles saved or something like that, not sure. cant understand why

**Comment by silvermcd123** [comment]
Well, no news about this? Maybe i will try a fix myself.

**Comment by Aokromes** [comment]
I think https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/DungeonFinding/LFGMgr.cpp#L432 something here is the culpit of lfd queue unable to requeue on someone leaves.
I blame https://github.com/TrinityCore/TrinityCore/pull/22321 @Ovahlord :troll:

**Comment by Aokromes** [comment]
requeue fixed by 7fb5233

**Comment by sirikfoll** [comment]
@jackpoz  Is there any need for detailed information on the "queue stuck" issue? (I seem to remember you had a patch to get more logs, but couldnt find it)
If it helps, I can try to get those logs.. still can't force it to happen, but here it happens naturally pretty much everyday ^^

**Comment by robinsch** [comment]
[](https://trello-attachments.s3.amazonaws.com/5d4c06eebcf19860ef2e8572/542x436/10fd301574d8ae04475e176be8bbdf2a/image.png)

**Comment by robinsch** [comment]
Example of "queue stuck"

https://imgur.com/a/wv57okA

**Comment by Shauren** [comment]
roles are not validated at all for joining queue - they come from client and must not be trusted to be always valid (you could modify packet to send no role or something invalid like mage tank)

**Comment by Aokromes** [comment]
[17:21:40] One or more dungeons was not valid.
Repo:
queue with 4, a separate member alone, queues as tank.
vote kick tank.
requeue.
find you forgot to change role of one member to be tank, stop queue.
with someone who want to be the tank try to requeue changing role to tank

https://i.imgur.com/MdkNkSJ.jpg

**Comment by robinsch** [comment]
There are also other parts where I created fallbacks for PLAYER_ROLE_NONE. Also I removed players for selection pool if they outlevel the dungeon level range. I will check tomorrow at peak times if people are still stuck in LFD queue.

**Comment by qyh214** [comment]
I have an issue:
player level is 80 and join random wlk dungeons ,the daily quest reward show is wrong,
xp should hide like common quest.

**Comment by jackpoz** [comment]
-  remove queue cd on kick. ada4e43

**Comment by jackpoz** [comment]
I opened a PR for the re-queue issue

**Comment by Faq** [comment]
+1 #24445

**Comment by jackpoz** [comment]
> roles are not validated at all for joining solo queue - they come from client and must not be trusted to be always valid (you could modify packet to send no role or something invalid like mage tank)

initial validation done by https://git.io/JfNa8

**Comment by jackpoz** [comment]
- [x] enter a lfg dungeon, 1 leaves, try to kick another, 1 agrees, 1 denies: vote doesn't end but waits till it expires f0f0de01fad0bc7bdfda215ec1a0f5b58d4a0ebf

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/5a3daf1694505cd71c24645d25a900963bb5c28f#diff-17691b06d029a6d50644ea56f35ceb814e8cbc94ddc85be2dfb767b972e81acfR26 - update the enum in this link. Someone on discord sent it to me.

**Comment by killerwife** [comment]
ServerToClient: SMSG_LFG_UPDATE_PARTY (0x0368)
Update Type: 5 (JoinProposal)
Extra Info: true
LFG Joined: false
Queued: false
Slot Count: 1
[0] LFG Entry: Full: 0x100011F Type: Dungeon Instance: 287
Comment: 

TC currently sends joined queued true on first join with group.

https://github.com/cmangos/mangos-wotlk/blob/master/src/game/LFG/LFGHandler.cpp#L309

**Comment by Aokromes** [comment]
small bug with queue.
queue with 5 persons into df
enter instance
kick one
queue with the 4 inside
re-queue with kicked one
it will re-ask accept to the people inside instance.

it don't must show the accept thing to people inside instance only to the one outside.

**Comment by killerwife** [comment]
Raid browser fully implemented in cmangos.

https://github.com/cmangos/mangos-wotlk/commit/9e14312e861a2165adbf9ed7908a9d61823cee54
https://github.com/cmangos/mangos-wotlk/commit/84c41fc3640bd7ecc513a72656204be4ed072647
https://github.com/cmangos/mangos-wotlk/commit/9a4626a179e0332f13b9731e6182d3d776725a95
https://github.com/cmangos/mangos-wotlk/commit/03ebc5fffac0d8d9cccc9c585ae0fb02619832b7

Rough idea what it requires, however, in WOTLK, raid browser doesnt support displaying roles for groups in client (even tho there is a payload for it) and nor does it support a rolecheck as I found after multiple hours sunk into it. So it only needs to "list" singular players and group players and enable sending the list results.
