### ISSUE TITLE
3.3.5a dberrors db_errors startup errors

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#14730]
```
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!
```

**Comment by ariel-** [comment]
> ```
Spell `39288` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39289` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39290` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
```

#14606 
should be fixed by #14611

**Comment by Killyana** [comment]
Error with the spell 63137 will be fixed with a PR.
An this will remove a useless related row.
``` sql
DELETE FROM `spell_target_position` WHERE `id`=63171;

**Comment by Killyana** [comment]
```
Table `creature_queststarter` has creature entry (14325) for quest 1318, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_queststarter` has creature entry (14325) for quest 7703, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_questender` has creature entry (14325) for quest 1318, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_questender` has creature entry (14325) for quest 7703, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
``` sql
UPDATE `creature_template` SET `NpcFlag`=3 WHERE `entry`=14325;

**Comment by fvicaria** [comment]
I have just updated the db and I still have these:

```
Spell `39288` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39289` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39290` of script `spell_kargath_executioner` does not have area aura effect - handler bound to hook `DoCheckAreaTarget` of AuraScript won't be executed
```

Is it correct or am I missing something?

**Comment by fvicaria** [comment]
I have just updated the db and I can still see these:
```
Spell `39288` of script `spell_kargath_executioner` does not have area aura effect - handler bound t
o hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39289` of script `spell_kargath_executioner` does not have area aura effect - handler bound t
o hook `DoCheckAreaTarget` of AuraScript won't be executed
Spell `39290` of script `spell_kargath_executioner` does not have area aura effect - handler bound t
o hook `DoCheckAreaTarget` of AuraScript won't be executed
```

Am I missing anything?

Thanks a lot!

**Comment by Killyana** [comment]
update your core.

**Comment by Killyana** [comment]
Error: Creature (GUID: 104706) does not exist but has a record in `creature_addon`
``` sql
DELETE FROM `creature_addon` WHERE `guid`=104706;

**Comment by Killyana** [comment]
ERROR [sql.sql] GOSSIP_OPTION_TRAINER:: Player Lacati (GUID: 173503) request wrong gossip menu: 0 with wrong class: 8 at Creature: William Saldean (Entry: 33996, Trainer Class: 0)
``` sql
UPDATE `creature_template` SET `trainer_type`=2 WHERE `entry` IN (33996);
DELETE FROM `npc_trainer` WHERE `ID`=33996;
INSERT INTO `npc_trainer` (`ID`, `SpellID`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqLevel`) VALUES
(33996, 2373, 500, 182, 50, 0),
(33996, 28696, 100000, 182, 275, 40),
(33996, 50301, 350000, 182, 350, 55),
(33996, 3571, 5000, 182, 125, 10),
(33996, 11994, 50000, 182, 200, 25),
(33996, 2372, 10, 0, 0, 0),
(33996, 74520, 500000, 182, 425, 75);

**Comment by Killyana** [comment]
.go crea 370785 and you will get this errors:
```
Gameobject (GUID: 164969 Entry: 175622) not created: non-existing entry in `gameobject_template`. Map: 229 (X: 83.030602 Y: -333.102997 Z: 91.489304)
Gameobject (GUID: 164970 Entry: 175622) not created: non-existing entry in `gameobject_template`. Map: 229 (X: 81.006302 Y: -332.454010 Z: 91.481400)
Gameobject (GUID: 164971 Entry: 175622) not created: non-existing entry in `gameobject_template`. Map: 229 (X: 79.001198 Y: -331.653015 Z: 91.471001)
Gameobject (GUID: 164972 Entry: 175622) not created: non-existing entry in `gameobject_template`. Map: 229 (X: 79.071999 Y: -328.433014 Z: 91.452904)

**Comment by ariel-** [comment]
I don't think it should be spawned though, see spell 16474

**Comment by Killyana** [comment]
It's not a spawn but the template.

**Comment by Killyana** [comment]
Fix an error about npc:18759  (SAI not requred as the aura was set on creature_template_addon, forgot to delete it)
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=18759 AND `source_type`=0;

**Comment by Killyana** [comment]
Error to fix:
Removing this script: https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/Kalimdor/zone_teldrassil.cpp#L39
Or maybe the hole file "zone_teldrassil.cpp"
```
Script named 'npc_mist' does not have a script name assigned in database.

**Comment by tkrokli** [comment]
The whole file "zone_teldrassil.cpp" is removed in commit efc4c60c53. Nothing in that file but the single script, so it was the logical choice.

**Comment by yvomsx** [comment]
Fix on the spell bp2 effect -

DELETE FROM `yvoworld`.`spell_linked_spell` WHERE  `spell_trigger`=48750 AND `spell_effect`=48770 AND `type`=2;

**Comment by Aokromes** [comment]
Not sure about the 1st, the 2nd needs to be scripted.

**Comment by yvomsx** [comment]
1st one works, i just tested it, and if someone could show me the retail version of brann ill script it :+1:

**Comment by Aokromes** [comment]
Jump into irc.

Anyway, this all must be moved into db:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp#L1257

**Comment by Killyana** [comment]
No, 48750 must trigger 48770, if you delete the link it will broke a quest.
