### ISSUE TITLE
[3.3.5] Core/Events: Some Holidays don't show in calendar

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#16845]
**Description:** Darkmoon Faire event does not show in calendar.

**Current behaviour:** (Tell us what happens)
Darkmoon Faire event does not show in calendar

**Expected behaviour:** (Tell us what should happen instead)
Darkmoon Faire event should show in calendar, like all other world events.

**Steps to reproduce the problem:**
1. Just open calendar and see it is not showing Darkmoon Faire.

**Branch(es):** 3.3.5

**TC hash/commit:** 8a95417

**TDB version:** 335.60

**Operating system:** Windows/Linux

**Comment by DDuarte** [comment]
This is a client limitation and there are no plans to modify the client's Holiday.dbc file.

**Comment by DDuarte** [comment]
There might be a way to do it with SMSG_CALENDAR_SEND_CALENDAR https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/CalendarHandler.cpp#L150-L173
This needs to be investigated...

**Comment by joschiwald** [comment]
you just need to send correct dates there, sending one date of a holiday will hide all events of the holiday loaded from client dbcs

![](http://i.imgur.com/D43IaC2.jpg)
3.3.5 client :)

**Comment by MrSmite** [comment]
Nice, I had tried editing my DBC once but that had less than desirable results.

FYI: Perhaps the title should be chagned to generic "Holidays don't show in calendar", I think it's more than Darkmoon that is effected in 335.

**Comment by sirikfoll** [comment]
looking forward to see this feature :+1:

**Comment by Kittnz** [comment]
@joschiwald have you done some testing with this?

**Comment by CrazyPeppers** [comment]
@joschiwald did you just edit column 11 (eventDate) to get the Darkmoon faire holiday date to update or were there additional columns or locations that need editing as well?

**Comment by chovie23q** [comment]
i can confirm that its not showing in the calender

**Comment by MrSmite** [comment]
@joschiwald - could you post your code so we can play around with it? Thanks!

**Comment by tkrokli** [comment]
So a fix for this issue is not about filling in more dates for the Darkmoon Faire event in the DB?

**Comment by MrSmite** [comment]
Just sending another ping to @joschiwald (assigned a year ago) to see if he can post his code.

**Comment by tkrokli** [comment]
After reading, rereading and rereading [joschiwald's comment](https://github.com/TrinityCore/TrinityCore/issues/16845#issuecomment-201851441) again at least 2 times more, I get the feeling he suggests to change the DB info to only contain 1 new single date of the occurrence to make it appear correctly in the Calendar (which implies that we need to commit a new DB update each month for Darkmoon Faire (Event 3+4+5) and maybe also for the Darkmoon Faire Building (23+71). Does this make sense, or have I completely misunderstood it?
```sql
SELECT * FROM `game_event` WHERE `description` LIKE '%Darkmoon%';
```
```
eventEntry           start_time             end_time  occurence  length  holiday  description                              world_event  announce
----------  -------------------  -------------------  ---------  ------  -------  ---------------------------------------  -----------  --------
         3  2016-11-06 00:01:00  2020-12-31 06:00:00     131040    8639      376  Darkmoon Faire (Terokkar Forest)                   0         2
         4  2016-12-04 00:01:00  2020-12-31 06:00:00     131040    8639      374  Darkmoon Faire (Elwynn Forest)                     0         2
         5  2017-01-01 00:01:00  2020-12-31 06:00:00     131040    8639      375  Darkmoon Faire (Mulgore)                           0         2
        23  2016-12-01 00:01:00  2020-12-31 06:00:00     131040    4320        0  Darkmoon Faire Building (Elwynn Forest)            0         2
        71  2013-01-06 01:01:00  2020-12-31 06:00:00     131040    8639        0  Darkmoon Faire Building (Mulgore)                  0         2
```

**Comment by MrSmite** [comment]
I don't know to be honest. I got the impression he forced a packet in code which is why I asked to see what he had done.

There are no events listed in my calendar at all for March / April yet we had Noblegarden that just ended and Children's week is starting soon. Also, Darkmoon hasn't appeared in my calendar since forever as well as the Stranglethorn Extravaganza events.

**Comment by tkrokli** [comment]
Well, let us hope he is in the mood to share some light on which parts of the source to modify to achieve results. Not sure if you noticed that he has declared his view on 3.3.5 as being dead to him compared to master.

**Comment by MrSmite** [comment]
Something I just noticed while browsing [GameEventMgr::LoadFromDB()](https://github.com/TrinityCore/TrinityCore/blob/255dd29562ae42a73c5947c2a8907faac888af31/src/server/game/Events/GameEventMgr.cpp#L215) is that the events are all loaded from `game_event` but never actually added to the calendar. It probably isn't that simple but who knows...

**Comment by MrSmite** [comment]
Looking at [CalendarHandler::GetCalendar()](https://github.com/TrinityCore/TrinityCore/blob/86b98686a95e23247ecb774fb23ecd5b8d94b97b/src/server/game/Handlers/CalendarHandler.cpp#L51) it appears to only load *playerEvents* and no world events. I would assume this is what sends the packet to the client when the calendar is opened?

**Comment by tkrokli** [comment]
Good question, I don't know. The wiki says this about **world_event**: "This is a Boolean field that determines if this game event is a world event or not. 0 = normal event, 1 = world event. For the world event to work, you need to at a minimum, populate game_event_condition and game_event_quest_condition." (I used to think that a world event would be any of the seasonal feasts, but now I don't know.)

BTW, in the table `game_event` the only rows with non-zero values in `world_event` are `Wintergrasp Alliance Defence` (48) and `Wintergrasp Horde Defence` (49) where the "Boolean" value is 5 ... 😕

**Comment by MrSmite** [comment]
Well perhaps I should've used *holdiay* instead of *world event* in my description.

Point still stands though that the events are loaded from `game_event` and never sent to the calendar and when you open the calendar it only sends *playerEvent* and *playerInvite* packets (if I read the code correctly).

**Comment by tkrokli** [comment]
OK, good point. Perhaps the core files need some rewriting for the calendar data to be handled correctly, maybe caused by other previous changes in the core.

**Comment by MrSmite** [comment]
Well, perhaps the problem is actually in *CalendarHandler::GetCalendar()*. It seems like it only tries to load event 666 and then nothing else, not to mention that Holidays.dbc doesn't have an ID of 666 in it.

```C++
    /// @todo Fix this, how we do know how many and what holidays to send?
    uint32 holidayCount = 0;
    data << uint32(holidayCount);
    for (uint32 i = 0; i < holidayCount; ++i)
    {
        HolidaysEntry const* holiday = sHolidaysStore.LookupEntry(666);

        data << uint32(holiday->Id);                        // m_ID
        data << uint32(holiday->Region);                    // m_region, might be looping
        data << uint32(holiday->Looping);                   // m_looping, might be region
        data << uint32(holiday->Priority);                  // m_priority
        data << uint32(holiday->CalendarFilterType);        // m_calendarFilterType

        for (uint8 j = 0; j < MAX_HOLIDAY_DATES; ++j)
            data << uint32(holiday->Date[j]);               // 26 * m_date -- WritePackedTime ?

        for (uint8 j = 0; j < MAX_HOLIDAY_DURATIONS; ++j)
            data << uint32(holiday->Duration[j]);           // 10 * m_duration

        for (uint8 j = 0; j < MAX_HOLIDAY_FLAGS; ++j)
            data << uint32(holiday->CalendarFlags[j]);      // 10 * m_calendarFlags

        data << holiday->TextureFilename;                   // m_textureFilename (holiday name)
    }
```

**Comment by MrSmite** [comment]
Update:

I've got replacement code for that block, just need to debug it. When you first open the calendar it works but when you change months it crashes the server.

**Comment by MrSmite** [comment]
Here's a diff for folks to play with. I'm having trouble pushing to github, I moved my development to a new machine and github is complaining about my ssl keys.

This works but the data in the calendar seems wrong, possibly missing data in `game_event`:

* *Noblegarden* that just happened in March is missing
* *Children's* Week coming up in May is missing
* Various *Call to Arms* events are listed perhaps too often?

```diff
From c90993496eef21f9f71981b13731fffa75094e0a Mon Sep 17 00:00:00 2001
From: MrSmite <bull@deadmines.cave>
Date: Tue, 4 Apr 2017 18:31:38 -0400
Subject: [PATCH 1/1] Fix calendar not showing holidays

---
 src/server/game/Handlers/CalendarHandler.cpp | 45 +++++++++++++++++-----------
 1 file changed, 28 insertions(+), 17 deletions(-)

diff --git a/src/server/game/Handlers/CalendarHandler.cpp b/src/server/game/Handlers/CalendarHandler.cpp
index 1a65433..44e997c 100644
--- a/src/server/game/Handlers/CalendarHandler.cpp
+++ b/src/server/game/Handlers/CalendarHandler.cpp
@@ -147,30 +147,41 @@ void WorldSession::HandleCalendarGetCalendar(WorldPacket& /*recvData*/)
     data << uint32(boundCounter);
     data.append(dataBuffer);
 
-    /// @todo Fix this, how we do know how many and what holidays to send?
-    uint32 holidayCount = 0;
-    data << uint32(holidayCount);
-    for (uint32 i = 0; i < holidayCount; ++i)
+    // TODO: GameEventMgr says holiday 0 is reserved but there are some entries in game_event such as
+    //       gurubashi arena run that perhaps should be included?
+    QueryResult result = WorldDatabase.Query("SELECT eventEntry, UNIX_TIMESTAMP(start_time), UNIX_TIMESTAMP(end_time), occurence, length, holiday, description, world_event, announce FROM game_event WHERE holiday > 0");
+
+    if (result)
     {
-        HolidaysEntry const* holiday = sHolidaysStore.LookupEntry(666);
+        data << uint32(result->GetRowCount());   // RowCount is uint64 but there should never be enough holidays that it can't fit into a uint32
+
+        // Now get actual holiday info and add to packet
+        do
+        {
+            Field* fields = result->Fetch();
+            HolidaysEntry const* holiday = sHolidaysStore.LookupEntry(fields[5].GetUInt32());
+
+            data << uint32(holiday->Id);                        // m_ID
+            data << uint32(holiday->Region);                    // m_region, might be looping
+            data << uint32(holiday->Looping);                   // m_looping, might be region
+            data << uint32(holiday->Priority);                  // m_priority
+            data << uint32(holiday->CalendarFilterType);        // m_calendarFilterType
 
-        data << uint32(holiday->Id);                        // m_ID
-        data << uint32(holiday->Region);                    // m_region, might be looping
-        data << uint32(holiday->Looping);                   // m_looping, might be region
-        data << uint32(holiday->Priority);                  // m_priority
-        data << uint32(holiday->CalendarFilterType);        // m_calendarFilterType
+            for (uint8 j = 0; j < MAX_HOLIDAY_DATES; ++j)
+                data << uint32(holiday->Date[j]);               // 26 * m_date -- WritePackedTime ?
 
-        for (uint8 j = 0; j < MAX_HOLIDAY_DATES; ++j)
-            data << uint32(holiday->Date[j]);               // 26 * m_date -- WritePackedTime ?
+            for (uint8 j = 0; j < MAX_HOLIDAY_DURATIONS; ++j)
+                data << uint32(holiday->Duration[j]);           // 10 * m_duration
 
-        for (uint8 j = 0; j < MAX_HOLIDAY_DURATIONS; ++j)
-            data << uint32(holiday->Duration[j]);           // 10 * m_duration
+            for (uint8 j = 0; j < MAX_HOLIDAY_FLAGS; ++j)
+                data << uint32(holiday->CalendarFlags[j]);      // 10 * m_calendarFlags
 
-        for (uint8 j = 0; j < MAX_HOLIDAY_FLAGS; ++j)
-            data << uint32(holiday->CalendarFlags[j]);      // 10 * m_calendarFlags
+            data << holiday->TextureFilename;                   // m_textureFilename (holiday name)
 
-        data << holiday->TextureFilename;                   // m_textureFilename (holiday name)
+        } while (result->NextRow());
     }
+    else
+        data << uint32(0);      // no results, holiday count 0
 
     SendPacket(&data);
 }
-- 
2.5.1.windows.1
```

**Comment by ariel-** [comment]
> Calendar stops at 2018 ("next" button becomes disabled)

WoW client calendar only shows next 2 years, if you change date on your computer then launch WoW again you'll notice

**Comment by MrSmite** [comment]
> WoW client calendar only shows next 2 years, if you change date on your computer then launch WoW again you'll notice

Interesting, thanks.

Update: Still working on getting correct fields. I updated the dates in my DB to 2017 based on wowhead.

**Comment by MrSmite** [comment]
Update:

Not having much luck with that date field. I've tried Uint64, Uint32, AppendPackedDate(), time_t and nothing works, it causes the client to completely freeze.

**Comment by sirikfoll** [comment]
@MrSmite You can try to improve this one, it basically works, but there's some issues, like mismatchs in the Darkmoon dates, maybe changing the duration of the game_event in DB solves it, it is currently set to last ~6 days, not 7
Ps: code in CalendarHandler.cpp is not mine, joschiwald helped with that

https://gist.github.com/sirikfoll/9dc48a323950bcce23641a64663712fb

**Comment by MrSmite** [comment]
@sirikfoll Thanks for the reference.

I think I may have found a simpler method using the `game_event` table and the *HolidaysEntry* struct, along with a bit from what you posted.

This time the events are loading and posting to the calendar without crashing or hangs. The bug now is that every event is listed as starting every hour of every day (yes, the tooltip shows 24 start times).

**Comment by MrSmite** [comment]
Update (before getting some sleep)

This code properly puts the start dates with the following bugs:

* No end dates are displayed
* Every raid resets every day at 8:21 am
* Every tile background combines the correct holiday tile along with the decorations from Winters Veil

```C++
    QueryResult result = WorldDatabase.Query("SELECT eventEntry, UNIX_TIMESTAMP(start_time), UNIX_TIMESTAMP(end_time), occurence, length, holiday, description, world_event, announce FROM game_event WHERE holiday > 0");

    if (result)
    {
        data << uint32(result->GetRowCount());   // RowCount is uint64 but there should never be enough holidays that it can't fit into a uint32

        // Now get actual holiday info and add to packet
        do
        {
            Field* fields = result->Fetch();
            HolidaysEntry const* holiday = sHolidaysStore.LookupEntry(fields[5].GetUInt32());

            data << uint32(holiday->Id);                        // m_ID
            data << uint32(holiday->Region);                    // m_region, might be looping
            data << uint32(holiday->Looping);              // m_looping, might be region
            data << uint32(holiday->Priority);                  // m_priority
            data << uint32(holiday->CalendarFilterType);        // m_calendarFilterType

            uint32 startTime = fields[1].GetUInt32();
            data.AppendPackedTime(startTime);

            for (uint8 j = 1; j < MAX_HOLIDAY_DATES; ++j)
                data << uint32(0);

            data << uint32(fields[4].GetUInt32());

            for (uint8 j = 1; j < MAX_HOLIDAY_DURATIONS; ++j)
                data << uint32(0);           // 10 * m_duration

            for (uint8 j = 0; j < MAX_HOLIDAY_FLAGS; ++j)
                data << uint32(holiday->CalendarFlags[j]);      // 10 * m_calendarFlags

            data << holiday->TextureFilename;                   // m_textureFilename (holiday name)

        } while (result->NextRow());
    }
    else
        data << uint32(0);      // no results, holiday count 0
```

**Comment by MrSmite** [comment]
@sirikfoll 

What are the constant values for in the diff you provided? I like to define them but I don't know what or how 60 was determined.

```C++
startTime += eventData.occurence * 60
```

```C++
uint32 holidayCount = 15;
```
Per wowhead, there are only 12 holidays. Or table `game_event` has 23 if you consider everything where `holiday`>0 and Holidays.dbc has 26 rows according to DBCTool.

**Comment by sirikfoll** [comment]
The 60 is a time transformation, "*60"(to seconds) and "/60"(to minutes)
In the original fix, i had a new table and stored the dates only for world events, so there where only 15 events sent, it worked better, i don't think that we need to send all the events in dbc.

But again, all is guessed, the ideal should be a sniff showing what was sent in the 3.3.5a version

**Comment by MrSmite** [comment]
So using your DIFF with *uint32 holidayCount = MAX_HOLIDAY_DATES;*, everything seems to work fine. I modified my holidays by changing everything to 2017 (I left the days and months the same).

NOTE: Raid reset and call to arms seem to spam the calendar regardless of which patch is used. Is this supposed to be this way?

**Comment by sirikfoll** [comment]
mine isn't working well yet, it doesn't show any of the call to arms, neither the weekend fishing events,
 and depending on the dates in DB, Darkmoon appear starting on saturdays
![image](https://cloud.githubusercontent.com/assets/11219553/24736336/cd64124c-1a5d-11e7-8519-57a45791f039.png)

**Comment by MrSmite** [comment]
This is what I get using your patch with the changes I mentioned above.

https://gist.github.com/MrSmite/3fa2c5daf35a98b60a8a822b75621b20

**Comment by Riztazz** [comment]
That date you're sending is not unix timestamp, it is packed time that you have to send 
http://www.cplusplus.com/reference/ctime/tm/ that is why yall probably getting weird results

**Comment by MrSmite** [comment]
> By the way, the time to next event has to be packed time

The patch provided by @sirikfoll works for the holidays, I'm not sure what the problem is with the other dates being spammed.

Also, the table has a start date (2017), a duration (days) and an end date (2020) so I don't really see why the core isn't capable of determining the proper dates when it loads the table.

**Comment by CrazyPeppers** [comment]
I don't know if this helps but I did notice when directly editing the dbc holidays that occurred after Feb seems to shift one day later then the values entered into the Holiday.dbc.  I figured it was something to due with a miscalculation for leap years.  Their epoch calendar does start on a leap year, could non-leap year be getting an extra day? Just an uneducated thought.

**Comment by MrSmite** [comment]
Ok, I just realized that the *Call to Arms* events have a holiday ID which probably explains why they're spammed. It seems like their duration / occurrence is wrong.

Also, here's the official list of holidays on [battle.net](http://us.battle.net/wow/en/game/events/)

**Comment by kaytotes** [comment]
Just thought i'd throw out my findings and what i've implemented so far. Hit a bit of a roadblock and ended up reverting this due to the battleground issues @MrSmite encountered.

https://github.com/kaytotes/NozdormuCore/commit/0c7a821c0917dfdd0f2d222fe4898a9bebb717dc

This implementation fixes the issues with the primary holidays being sent to the client as well as upgrading the start dates, length and occurrence to match the dates I had on the calendar when logged in on retail.

The start date and start time work correctly as does the end date but the end time still seems to be reading from the client or possibly isn't calculated properly from the length of the holiday.

The issue with the battleground holidays still persists but I did a bit of tinkering with this by setting all the BG weekends to start way in the future just to clean up the calendar. Then reset WSG and it repeats itself. A weekend restarts the minute it ends on the calendar. Adjusting length or occurrence made no difference.

I think this is about as far as i'm going to get on this as I simply don't know enough about the packets and I couldn't get a sniffer working on the latest retail build for some reason.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/951fa46fe9b14a9e275ac9306b2346959e40e3e5

**Comment by Hangasilly** [comment]
Sorry folks, that i reopen now... 
But i got the same issue at least: there are some worldevents, that are not shown in my ingame-calendar...
So i asked google and it showed me this discussion.

I surely read all and just tried MrSmite told on 4th of April 17, but nothing is fixed now on my server...

The link of kaytotes is broken and the issue still exists for me...

Perhaps it's my knowledge about english and i did anything wrong, but i don't know...
So i hope, that anyone could tell me **easily** what to do to fix this issue...
