### ISSUE TITLE
DB/GameObject: Hallow's End achievement Tricks and Treats of ...

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18104]
**Description**: Tricks and Treats of Kalimdor World Event Achievement list includes Silverwind Refuge in Ashenvale when in some previous version, that particular candy bucket was pulled. (See photo) Cannot locate candy bucket in this commit, 

**Current behaviour**: Player runs around Silverwind Refuge in circles searching for a candy bucket that is not there. (Not sure if it is SUPPOSED to be there, or if its supposed to be off the achievement list.)

**Expected behaviour**: If it supposed to be off the list, one shouldn't be directed to search for the Candy bucket in Silverwind Refuge. If there is supposed to be a bucket there, it's not. :)

**Steps to reproduce the problem**:
1. Work toward Tricks and Treats of Kalimdor Achievement
2. Fly or .tele to Silverwind Refuge.
3. Look for candy bucket.
4. Give up and update TC / Github.

Further investigation reveals that someone up and quit placing these candy buckets as they are missing in the remainder of the camps in Kalimdor. To be specific they are:

1) Grol'dom Farm
2) Hellscream's Watch
3) Camp Ataya
4) Stonemaul Hold
5) Bilgewater Harbor
6) Nozzlepot's Outpost
7) Desolation Hold
8) Krom'gar Fortress
9) Zoram'gar Outpost
10) Karnum's Glade (Horde AND Alliance)
11) Whisperwind Grove
12) Bootlegger Outpost
13) Marshal's Stand

**Branch(es)**: 6.x - Have not tried in 3.x yet

**TC hash/commit**:   TrinityCore rev. c676e80 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version**:  7.04

**Operating system**:  Win 10 

http://i.imgur.com/1rSDY1z.jpg

**Comment by BahDumbBugs** [comment]
After dealing a bit more with these Hallow's End quests and Achievements, I stumbled across a few curious glitches/bugs. In the 'Tricks and Treats of Outland' segment of the Achievement, there are only two that can't be completed right off the bat. Those are the two that have to do with whether you choose allegiance with Scryers or Aldors. I have not established reputation with either faction and will be testing it shortly. With these two, however, the pumpkins are there, they are selectable (depending on your friendly status) but it will not reward you with the 'Handful of Treats' and complete that segment of the quest. More to come.....

**Comment by BahDumbBugs** [comment]
In Northrend:

1) Taunka'le Village and Kamagua among others I am sure (I will validate shortly) are showing the Candy Buckets as a Daily Quest (Blue Question Mark above). They are present and selectable, but when the Handful of Treats dialogue box opens up, you cannot select "Complete Quest" to finish and receive rewards.

2) In Bor'gorok Outpost the Candy Bucket is in the middle of the Apple Bob tub. Slight location adjustment is necessary. Candy Bucket is correctly represented with a yellow Question Mark quest indicator and normal in behavior, however.

**Comment by BahDumbBugs** [comment]
Cataclysm (I know not all areas are implemented yet. This is just for posterity):

1) Nordrassil does not have a Candy Bucket present in its proper location.
2) Oasis of Vir'sar has no Candy Bucket in its proper location.
3) Deepholm (Not Implemented yet) - Cannot locate Candy Bucket in Temple of Earth

More to come......

**Comment by BahDumbBugs** [comment]
After dealing a bit more with these Hallow's End quests and Achievements, I stumbled across a few curious glitches/bugs. In the 'Tricks and Treats of Outland' segment of the Achievement, there are only two that can't be completed right off the bat. Those are the two that have to do with whether you choose allegiance with Scryers or Aldors. I have not established reputation with either faction and will be testing it shortly. With these two, however, the pumpkins are there, they are selectable (depending on your friendly status) but it will not reward you with the 'Handful of Treats' and complete that segment of the quest. More to come......

**Comment by BahDumbBugs** [comment]
In Northrend:

1) Taunka'le Village and Kamagua among others I am sure (I will validate shortly) are showing the Candy Buckets as a Daily Quest (Blue Question Mark above). They are present and selectable, but when the Handful of Treats dialogue box opens up, you cannot select "Complete Quest" to finish and receive rewards.

2) In Bor'gorok Outpost the Candy Bucket is in the middle of the Apple Bob tub. Slight location adjustment is necessary. Candy Bucket is correctly represented with a yellow Question Mark quest indicator and normal in behavior, however.

**Comment by BahDumbBugs** [comment]
Cataclysm (I know not all areas are implemented yet. This is just for posterity):

1) Nordrassil does not have a Candy Bucket present in its proper location.
2) Oasis of Vir'sar has no Candy Bucket in its proper location.
3) Deepholm (Not Implemented yet) - Cannot locate Candy Bucket in Temple of Earth

More to come......

**Comment by funjoker** [comment]
Well I'm on some Bucket decoration stuff ^^...
Might just take some time

**Comment by Kittnz** [comment]
@funjoker 335 or 7.x?

**Comment by funjoker** [comment]
7.x

**Comment by BahDumbBugs** [comment]
Cool. Good to see some planning going on. I'll continue to find the nasty bugs and squish em. :)

**Comment by MrSmite** [comment]
> @funjoker 335 or 7.x?

> 7.x

Unfortunately these holidays are largely broken in 335 too. Will this be able to be backported?

**Comment by BahDumbBugs** [comment]
I should throw on 335 as well and do the same quests. COmpare/contrast works/fixes/bugs

**Comment by Kittnz** [comment]
Everything works in Northrend that is mentioned here on 335. What exactly are you working on @funjoker ?

**Comment by Aokromes** [comment]
Maybe some cherry picks are missing on 7.x

**Comment by Kittnz** [comment]
And what exactly doesn't work on 335 @MrSmite ?

**Comment by funjoker** [comment]
Do Not take spawns of eastern kingdoms and kalimdor to 7.x. Cata fucked it up.

Atm i sniff all candy bucket decoration things.
Trying to make a proper List.

**Comment by Kittnz** [comment]
i think iv done that last year. got both kingdoms

**Comment by funjoker** [comment]
well didn't check yet :D atm just sniffing ^^

**Comment by funjoker** [comment]
Is it possible, that you only sniffed the Cata areas and not the whole kingdom?
atm i could only find decoration and bucket in Twilight Highlands

**Comment by funjoker** [comment]
seems like you only did Horde decoration :(

**Comment by Kittnz** [comment]
Well i didn't do anything for 7.x only 335.

**Comment by funjoker** [comment]
My Work so far:

- [ ] Eastern Kingdom - Alliance
- [ ] Eastern Kingdom - Horde
- [ ] Kalimdor - Alliance
- [ ] Kalimdor - Horde
- [ ] Outlands - Alliance
- [ ] Outlands - Horde
- [ ] Northrend - Alliance
- [ ] Northrend - Horde
- [ ] Cataclysm - Alliance
- [ ] Cataclysm - Horde
- [ ] Pandaria - Alliance
- [ ] Pandaria - Horde

Didn't check ingame stuff.
Outland and Northrend might be already implemented

**Comment by MrSmite** [comment]
> And what exactly doesn't work on 335 @MrSmite ?

I was thinking of the quests to put out the fire in Goldshire. You can get the quests from the Matron but nothing spawns. I didn't realize there was a separate report for that bug.

**Comment by BahDumbBugs** [comment]
@Aokromes , @tkrokli Would it be more helpful or less to have all the Hallow's end glitches in one ticket?

**Comment by tkrokli** [comment]
That depends on how connected & how close they are, like if they are handled by the same script file, SAI script, database table etc. Keep issues separate if they don't affect the same NPC(s) or script.

**Comment by BahDumbBugs** [comment]
So the procedure of rolling all the Treat buckets issues like these are good? (Im telling myself "Yes - otherwise there'd be a lot of noise about it by now. :) )

**Comment by BahDumbBugs** [comment]
In Northrend:

## Alliance Side
1) The following camps/points are showing the Candy Buckets as a Daily Quest (Blue Question Mark above). They are present and selectable, but when the Handful of Treats dialogue box opens up, you cannot select "Complete Quest" to finish and receive rewards.

-




The remainder are fine. (XX in Northrend.)

**Comment by Kittnz** [comment]
Give me a few example's of locations

**Comment by MrSmite** [comment]
> Give me a few examples of locations.

While not a blue ?, the candy buckets in Stormwind, Goldshire and Lakeshire allowed me to do them twice each on a Paladin and Hunter (though I doubt it's a class issue). After two completions I now do not see the ? anymore.

**Comment by BahDumbBugs** [comment]
Exactly @MrSmite . Theyre a one time deal from what Ive gone through during years on retail. AFter I did them once, I always got the generic "Greetings Threepwood" message. @Kittnz - Alliance side I have not gotten to yet. I left that there as a placeholder. Wanted to focus on Horde side first. I momentarily digressed to 3.3.5 for a moment to test a few things before dinner. I'll have an update for Alliance side (and tests) shortly. :)

**Comment by BahDumbBugs** [comment]
@MrSmite - What commit are you using and version? Im getting hardly anything on Alliance side. (See list above)

**Comment by BahDumbBugs** [comment]
> "While not a blue ?, the candy buckets in Stormwind, Goldshire and Lakeshire allowed me to do them twice each on a Paladin and Hunter (though I doubt it's a class issue). After two completions I now do not see the ? anymore."

What version was that? 6.x or 3.3.5?

**Comment by tkrokli** [comment]
@BahDumbBugs : MrSmite has usually focused on 3.3.5 in the past, but I don't know about now.

Myself, I was able to access the candy bucket in Falconwing Square 2 times in a row on commit https://github.com/TrinityCore/TrinityCore/commit/10ca86edc51be285a7381d35178da10686eb88ee , my TC rev. hash before I pushed the commit to fix the quest "Completing the Delivery". Not tested after.

**Comment by MrSmite** [comment]
@BahDumbBugs 

I'm using https://github.com/TrinityCore/TrinityCore/commit/2db9269ec1c06b5fccc45dc0a5b4f714f9b48804 with DB TDB_full_world_335.61_2016_04_11.sql + updates

On that revision I can access the candy buckets 2 times per character per login (eg: it resets after I log out) and they only display the standard yellow "?".

**Comment by Kittnz** [comment]
I think that changed not too long ago

**Comment by BahDumbBugs** [comment]
Checking all Candy Buckets on my commit is complete. I don't know how we can verify all these treat buckets short of going through them one by one. Is there any way we can validate all these issues existing for the treat buckets? Please let me know if I am wrong on any of these or missed anything. Thanks!

**Comment by BahDumbBugs** [comment]
@MrSmite - I think @Kittnz is right. I can park at an inn with a blue question mark, try to get it - log out and come back and it will still show blue.

**Comment by Kittnz** [comment]
Either way, this is about 7.x not 3.3.5.

**Comment by funjoker** [comment]
Check this:

#18134

**Comment by jerbookins** [comment]
f909d4f1957b

No Candy Bucket quests work.

**Comment by meji46** [comment]
Added missing Candy buckets (Kalimdor & Eastern Kingdoms) and fixed quests that couldn't be completed (Northrend)
