### ISSUE TITLE
Quest Cold Hearted 

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20014]
**Description:**
The flying speed of the Freed Proto-Drakes is incredibly slow. And you seemingly cannot fly upward or downward.
http://www.wowhead.com/quest=12856/cold-hearted

**Current behaviour:**
This video shows the slow movement speed of the drakes.
https://gfycat.com/TightOccasionalFanworms

**Expected behaviour:**
This video shows the expected movement speed of the drakes.
https://www.youtube.com/watch?v=y25EOTX0M-Q

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
1f834d3cd195

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

**Comment by Killyana** [comment]
Use space and X to change the altitude, it will also fix the vehicle speed.
It's a general issue for all flying vehicles.

**Comment by jerbookins** [comment]
I pressed X and space a million times.

**Comment by jerbookins** [comment]
That is until you reach the checkpoint where the drake slowly and painfully flies itself back

**Comment by Foereaper** [comment]
I have fixed this locally but will have to conduct some testing on a clean source to verify that it works as intended. Will give a heads up whenever I have done this.

**Comment by Foereaper** [comment]
Should I open a new issue to have the above query pulled in?

**Comment by Rushor** [comment]
@Foereaper you must update it to creature_template_movement now

**Comment by illfated** [comment]
```sql
SELECT * FROM `creature_template_movement` WHERE `CreatureId`= 29709;
```
```sql
CreatureId  Ground    Swim  Flight  Rooted   Chase  Random  InteractionPauseTimer
----------  ------  ------  ------  ------  ------  ------  ---------------------
   29709       0       0       1       0       0       0         (NULL)
```

**Comment by CraftedRO** [comment]
86551ba71669712cadf82f2dc1f0c5481f0fba1b issue still valid, is missing some core vehicle flightspeed feature, db creature_template walk and run speed are sniffed.

> [1] MoverGUID: Full: 0x243CD047601D0300000015000051F4FF Vehicle/0 R3892/S21 Map: 571 (Northrend) Entry: 29708 (Captive Proto-Drake) Low: 5371135
> [1] MovementFlags: 512 (DisableGravity)
> [1] MovementFlags2: 15 (NoStrafe, NoJumping, FullSpeedTurning, FullSpeedPitching)
> [1] MovementFlags3: 0 (None)
> [1] MoveTime: 3162714346
> [1] Position: X: 7148.0425 Y: -2681.334 Z: 849.6174
> [1] Orientation: 4.24873208999633789
> [1] Pitch: 0
> [1] StepUpStartElevation: 0
> [1] MoveIndex: 0
> [1] HasStandingOnGameObjectGUID: False
> [1] Has Transport Data: False
> [1] Has Fall Data: False
> [1] HasSpline: True
> [1] HeightChangeFailed: False
> [1] RemoteTimeValid: False
> [1] HasInertia: False
> [1] HasAdvFlying: False
> [1] WalkSpeed: 8
> [1] RunSpeed: 10
> [1] RunBackSpeed: 4.5
> [1] SwimSpeed: 4.72221994400024414
> [1] SwimBackSpeed: 2.5
> [1] FlightSpeed: 7

**Comment by CraftedRO** [comment]
86551ba71669712cadf82f2dc1f0c5481f0fba1b issue still valid, is missing some core vehicle flightspeed feature, db creature_template walk and run speed are sniffed.

> [1] MoverGUID: Full: Vehicle/0 R3892/S21 Map: 571 (Northrend) Entry: 29708 (Captive Proto-Drake) Low: 5371135
> [1] MovementFlags: 512 (DisableGravity)
> [1] MovementFlags2: 15 (NoStrafe, NoJumping, FullSpeedTurning, FullSpeedPitching)
> [1] MovementFlags3: 0 (None)
> [1] MoveTime: 3162714346
> [1] Position: X: 7148.0425 Y: -2681.334 Z: 849.6174
> [1] Orientation: 4.24873208999633789
> [1] Pitch: 0
> [1] StepUpStartElevation: 0
> [1] MoveIndex: 0
> [1] HasStandingOnGameObjectGUID: False
> [1] Has Transport Data: False
> [1] Has Fall Data: False
> [1] HasSpline: True
> [1] HeightChangeFailed: False
> [1] RemoteTimeValid: False
> [1] HasInertia: False
> [1] HasAdvFlying: False
> [1] WalkSpeed: 8
> [1] RunSpeed: 10
> [1] RunBackSpeed: 4.5
> [1] SwimSpeed: 4.72221994400024414
> [1] SwimBackSpeed: 2.5
> [1] FlightSpeed: 7
