### ISSUE TITLE
Core/Spells: Players are able to fail while gathering

### ISSUE THREAD

**Issue by BittyBit** [TrinityCore/TrinityCore#21038]
**Description:** Players are able to fail while gathering

**Current behaviour:**

Players can fail when attempting to skin a mob, mine a node or pick a flower

**Expected behaviour:**

Per the 3.1.0 patch notes (http://www.wowhead.com/patchnotes=3.1.0):

You can no longer fail when Mining, Herbing, and Skinning.

**Steps to reproduce the problem:**

Attempt to gather enough skins, ores or herbs and you will see failed attempts.

Due to the random nature of failing when gathering it will only happen once in a while. You will have a greater chance at reproducing the issue on 'orange' level resources.

**Branch(es):** 3.3.5 (not tested on master)

**TC rev. hash/commit:**

TrinityCore rev. 97f33dc 2017-11-11 20:27:30 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)

**Operating system:** Ubuntu 16.04LTS

**Comment by tkrokli** [comment]
TrinityCore rev. 8ccf905f403b 2017-12-09 00:29:53 +0100 (3.3.5 branch) (Win64, Release, Static)
Confirmed. This can be confirmed on any available 3.3.5 core rev. hash for the last 3-4 years, maybe more.
I do not know what the solution looks like, but it should be fixed to make the behaviour more blizzlike.

**Comment by Ovahlord** [comment]
It is blizzlike. This case is even manually coded in the core. Fail attempts does not exist since Cata anymore. On WotLK they were still present.

**Comment by tkrokli** [comment]
I'm confused. Do you mean that even though the 3.1.0 patch notes said it was changed, it was still unchanged in the game until Cataclysm?

**Comment by tkrokli** [comment]
Meh. Another wasted opportunity to get something fixed that I thought was broken.

**Comment by Ovahlord** [comment]
This is at least what I heard so far. I just googled arround at it seems that indeed gathering is not suposed to fail anymore since 3.(dunno when exactly)

**Comment by BittyBit** [comment]
> I just googled arround at it seems that indeed gathering is not suposed to fail anymore since 3.(dunno when exactly)

3.1.0 as per the patch notes. I didn't want to link actual battle.net resources so I thought posting wowhead patch notes (that they copied verbatim from blizz) would suffice as canon.

**Comment by tkrokli** [comment]
Might need to come up with some even more heavy-hitting documentation to make the case water tight. Or a confirmation from one of the TC owners.

**Comment by Ovahlord** [comment]
http://us.battle.net/wow/en/game/patch-notes/3-1-0

> You can no longer fail when Mining, Herbing, and Skinning.

**Comment by tkrokli** [comment]
Looks like I'm displaying symptoms of the "2017 disease", being wrong and then being wrong again (thinking that I made a mistake, but that was a mistake too). :-P

**Comment by Ovahlord** [comment]
Well, it was also my mistake since I just saw things related to it why reading about archaeology

**Comment by tkrokli** [comment]
Thank you to all involved, especially to @Ovahlord for the PR and @BittyBit for pointing out this issue. This will certainly make my in-game gathering less annoying! 😄
