### ISSUE TITLE
[3.3.5] Lich King

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21695]
**Description:**

Lich king in the textures. GEODATA has been updated today
![image](https://user-images.githubusercontent.com/37352351/37902349-dbfbbb0a-30fc-11e8-822d-80382e46b914.png)

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/fb31cb7c047f4d79e7bea04b72175e6ef251a317

**Comment by Aokromes** [comment]
stop ignoring the request of use server debug command.

**Comment by vahzxz** [comment]
@Aokromes I don't understand about what you say pliz write more, or throw off the link. Or on Skype vanz7796

**Comment by Killyana** [comment]
The revision is not visible.

**Comment by meji46** [comment]
Client is loading creature (Lich King) before gameobject (platform). For that reason it falls through the gameobject.

Maybe the server should send the gameobjects in UPDATE_OBJECT first and then the npcs to avoid this problem.

**Comment by vahzxz** [comment]
@meji46 How can I solve this problem?

**Comment by vahzxz** [comment]
@Killyana 
![image](https://user-images.githubusercontent.com/37352351/37904986-16d9cc40-3106-11e8-963a-796259d54f8f.png)

**Comment by vahzxz** [comment]
I don't know why, but I always have problems with GEODATA, although GEODATA are collected properly and without errors. Let's say right now, rebooted the server LICH as expected at the facility is. And now I will reload it already below once again.

**Comment by Killyana** [comment]
This issue was fixed is the same as https://github.com/TrinityCore/TrinityCore/issues/16330 it was fixed by https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25
And I cannot reproduce it on rev. fb31cb7c047f

**Comment by vahzxz** [comment]
@Killyana Should I roll this fix?https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Comment by Killyana** [comment]
No, you have an issue with your core.

**Comment by vahzxz** [comment]
@Killyana How can I have problems with the kernel if I have already shown you the revision version of the database showed. Even now for fun on new source download and compile, although in the 2 days 3 times it did. The problem remains. I really can't figure out how to solve it.

**Comment by Killyana** [comment]
No Idea, I see just issues that we are not able to reproduce, so something is wrong with your core.

**Comment by vahzxz** [comment]
![image](https://user-images.githubusercontent.com/37352351/37907721-9aa31a38-310e-11e8-86a2-9966463736d4.png)
Again shake the core. After a few minutes, will throw off a screenshot compilation.

**Comment by vahzxz** [comment]
@Killyana You can ask for a database with the latest updates at the moment. Thank you in advance. There's just a suspicion there's a problem with her.

**Comment by vahzxz** [comment]
All completely from scratch collected. Database thanks. Still the same situation

**Comment by vahzxz** [comment]
![image](https://user-images.githubusercontent.com/37352351/37912308-eec923c6-311a-11e8-86d4-be05cfedbf9e.png)

**Comment by Faq** [comment]
Any custom patches applied?
try with https://github.com/TrinityCore/TrinityCore/pull/21658

**Comment by vahzxz** [comment]
@Faq The core is completely clean. With the latest updates, so that the Commits offered is not up to date

**Comment by Killyana** [comment]
Last thing before closing this issue, provide .npc info data related to Movement type (from a val'kyr), I suspect the sql used to create creature_movement and convert old inhabit_type executed twice.

**Comment by vahzxz** [comment]
I was confused when downloading the database this line
![image](https://user-images.githubusercontent.com/37352351/37922669-e28f0f60-3135-11e8-990f-6311fd0a95e6.png)
Behold server info
![image](https://user-images.githubusercontent.com/37352351/37922919-90e1f820-3136-11e8-97ac-e21870feb82b.png)
![image](https://user-images.githubusercontent.com/37352351/37922947-9fc6c5d2-3136-11e8-88ab-dc85e533db8d.png)
![image](https://user-images.githubusercontent.com/37352351/37922979-af503c22-3136-11e8-8839-8aa95143167e.png)
![image](https://user-images.githubusercontent.com/37352351/37922999-bbb60208-3136-11e8-9176-3910aa1dd0bb.png)

**Comment by vahzxz** [comment]
@Killyana Before you close this problem can please throw off your database with the latest updates. Maybe I'm just really not properly rolled updates. Thank you in advance.

**Comment by vahzxz** [comment]
@Killyana https://github.com/TrinityCore/TrinityCore/issues/21695#issuecomment-376252219
And the fact that not discovered this table so it should be?)

**Comment by tkrokli** [comment]
@vahzxz : download the file `TDB_full_world_335.64_2018_02_19.7z`
from https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.64
then unzip it with 7zip or WinRAR to a folder you can manage
and only use the file `TDB_full_world_335.64_2018_02_19.sql` in your core folder,
so DB auto updater can load it and all the world updates from
https://github.com/TrinityCore/TrinityCore/tree/3.3.5/sql/updates/world/3.3.5
(which should be part of your source code when compiling).

**Comment by vahzxz** [comment]
@tkrokli And such question still. And the database folder updates reinvents itself or it is necessary manually to download updates?

**Comment by tkrokli** [comment]
Please don't install any updates manually. DB auto updater will load them all if you start off with default values from compiling the source code on the same computer as the one you run your core on. Use default settings in all files to see that it works as intended & expected before you make any changes to any of the settings.

BTW, this is personal configuration and should not be part of the TrinityCore issue tracker. Use the TrinityCore Forum pages (https://community.trinitycore.org/) or ask in IRC (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC) if you need answers besides the information in the wiki pages (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130076/Core+Installation).
