### ISSUE TITLE
[3.3.5a] [Hunter Pets] Tamed Pets cannot pass level 75

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23563]
Hunter Pets cannot level 75+. If you tame a pet Level 75, you no longer have experience bar. Even if you try killing level 80 Targets, your pet still remains at 75, without any advancements in experience and level.

**Current behaviour:**
Hunter pets max level is 75,  the only way to level a pet is using GM Commands .pet level 5

**Expected behaviour:**
Hunter Pets should be able to match the level of an owner, your pet must level 75-80.

**Steps to reproduce the problem:**

1. Make a Hunter 
2. Go to Northrend and tame a level 75 Creature.
3. Try leveling your pet from 75 to 76
4. Look at pet's experience bar
5. Notice Pet not leveling or receiving any experience from kills

**Branch(es):**
Branch 3.3.5a
Rev: f44539b64247ff626c53dc899c4ac3023bf9aa80

**Comment by Wyrserth** [comment]
Cannot reproduce this issue, tried taming a few pets and they all receive experience normally.

Can you try again with a fresh TC build and tell us which creatures you're encountering this issue with?

**Comment by Killyana** [comment]
Yes, confirm it works correctly in rev. 7fc1ecca8a32
It's weird, I'm pretty sure it wasn't the case yesterday.

**Comment by RR2739-VCN** [comment]
Clean TC, Pets do not level past level 75, I tried it with clean DB, Clear Source. It doesnt matter which pet, leveling works fine up until 75. I am not sure how you were able to get past 75, because your pet's experience doesn't show going up

**Comment by Wyrserth** [comment]
[Here's a freshly tamed level 75 pet earning exp](https://imgur.com/a/9GB3dHB).

It could be that the issue was fixed as a side effect of fixing other bugs, please test again on 515f47eec7263bfb593a2697c0be8afa40ed0324 to be sure.

**Comment by RR2739-VCN** [comment]
SetByteValue(PLAYER_BYTES_3, PLAYER_BYTES_3_OFFSET_INEBRIATION, fields[54].GetUInt8());
Fixes pet leveling?

Because we tested this with almost every pet type last night and couldnt level anything past 75.

**Comment by jackpoz** [comment]
could you try to reproduce the issue at https://tcubuntu.northeurope.cloudapp.azure.com ?

**Comment by RR2739-VCN** [comment]
The issue is still there, I cannot level a pet past level 75, watch experience not going up, you can never level it. Killing lvl 80 creatures. 0 experience

![image](https://user-images.githubusercontent.com/47407621/60990195-babe4200-a2fc-11e9-85d5-d51f28cc0b76.png)

**Comment by Wyrserth** [comment]
Did you try killing it with .die or .damage?

That the pet becomes level 75 instead of 80 is blizzlike, pet becomes yourlevel-5 if its level when tamed is lower than that.

**Comment by RR2739-VCN** [comment]
I did regular dmg using a spell dmg6 , i tried every single pet and i cannot level any pets no matter what level they are.

![image](https://user-images.githubusercontent.com/47407621/60991573-a0d22e80-a2ff-11e9-91ba-8989c376bfbe.png)

**Comment by Aokromes** [comment]
https://i.imgur.com/4uoErR5.png cannot reproduce near head, update your core if you still have problems.
