### ISSUE TITLE
[QUEST] Escape from the Staging Grounds (10425)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#3724]
The escort part is probably not scripted, the Captured Protectorate Vanguard ( http://old.wowhead.com/npc=20763 ) NPC just stands there and attacks the nearby NPCs.

TDB42 up to 0ef92d8

**Comment by RedSonja** [comment]
Any word on this one?

**Comment by Rushor** [comment]
```sql
-- Captured Protectorate Vanguard SAI
SET @ENTRY := 20763;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,19,0,100,0,10425,0,0,0,1,0,0,0,0,0,0,21,10,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Quest 'Escape from the Staging Grounds' Taken - Say Line 0"),
(@ENTRY,0,1,2,61,0,100,0,10425,0,0,0,53,0,20763,0,0,0,2,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Quest 'Escape from the Staging Grounds' Taken - Start Waypoint"),
(@ENTRY,0,2,14,61,0,100,0,10425,0,0,0,64,1,0,0,0,0,0,21,10,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Quest 'Escape from the Staging Grounds' Taken - Store Targetlist"),
(@ENTRY,0,7,0,40,0,100,0,121,20763,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 121 Reached - Pause Waypoint"),
(@ENTRY,0,8,10,40,0,100,0,123,20763,0,0,15,10425,0,0,0,0,0,12,1,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 123 Reached - Quest Credit 'Escape from the Staging Grounds'"),
(@ENTRY,0,9,0,6,0,100,0,0,0,0,0,6,10425,0,0,0,0,0,12,1,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Just Died - Fail Quest 'Escape from the Staging Grounds'"),
(@ENTRY,0,10,0,61,0,100,0,123,20763,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 123 Reached - Say Line 1"),
(@ENTRY,0,11,12,40,0,100,0,125,20763,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 125 Reached - Say Line 2"),
(@ENTRY,0,12,13,61,0,100,0,125,20763,0,0,11,35517,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 125 Reached - Cast 'Teleport'"),
(@ENTRY,0,13,0,61,0,100,0,125,20763,0,0,41,3000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Waypoint 125 Reached - Despawn In 3000 ms"),
(@ENTRY,0,14,0,61,0,100,0,10425,0,0,0,81,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Quest 'Escape from the Staging Grounds' Taken - Set Npc Flag "),
(@ENTRY,0,15,0,11,0,100,0,0,0,0,0,81,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Captured Protectorate Vanguard - On Respawn - Set Npc Flag Questgiver");

DELETE FROM `creature_text` WHERE `entry`=20763;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `comment`) VALUES
(20763, 0, 0, 'We''re not too far from the Protectorate Watch Post, $n. This way!', 12, 0, 100, 0, 0, 0, 18566, 'Captured Protectorate Vanguard to Player'),
(20763, 1, 0, 'Commander! This fleshling rescued me!', 12, 0, 100, 0, 0, 0, 18567, 'Captured Protectorate Vanguard to Player'),
(20763, 2, 0, '%s salutes Commander Ameer.', 16, 0, 100, 0, 0, 0, 18568, 'Captured Protectorate Vanguard to Player');

DELETE FROM `waypoints` WHERE `entry`=20763;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (20763,1,4062.889,2301.426,112.589,''),
(20763,2,4072.389,2299.926,112.089,''),
(20763,3,4077.389,2299.426,111.339,''),
(20763,4,4081.389,2298.676,111.089,''),
(20763,5,4087.389,2297.926,110.339,''),
(20763,6,4087.522,2297.531,110.1197,''),
(20763,7,4089.272,2297.281,109.8697,''),
(20763,8,4093.272,2297.031,109.1197,''),
(20763,9,4096.272,2297.031,108.3697,''),
(20763,10,4099.272,2297.031,107.8697,''),
(20763,11,4104.022,2297.031,107.1197,''),
(20763,12,4112.022,2296.531,106.6197,''),
(20763,13,4088.517,2298.271,109.8349,''),
(20763,14,4092.017,2298.021,109.3349,''),
(20763,15,4095.017,2297.771,108.8349,''),
(20763,16,4116.249,2296.554,105.7884,''),
(20763,17,4120.249,2296.554,105.0384,''),
(20763,18,4125.249,2296.804,104.5384,''),
(20763,19,4131.999,2296.804,104.0384,''),
(20763,20,4136.999,2296.804,103.5384,''),
(20763,21,4145.999,2297.054,103.0384,''),
(20763,22,4117.687,2297.917,105.4414,''),
(20763,23,4122.437,2297.917,104.9414,''),
(20763,24,4146.189,2297.527,102.9234,''),
(20763,25,4149.439,2297.527,102.9234,''),
(20763,26,4163.939,2300.277,103.4234,''),
(20763,27,4166.939,2300.777,104.4234,''),
(20763,28,4170.689,2301.777,104.9234,''),
(20763,29,4172.689,2302.027,105.6734,''),
(20763,30,4172.918,2302.12,105.9335,''),
(20763,31,4174.668,2302.37,106.6835,''),
(20763,32,4176.668,2302.37,107.4335,''),
(20763,33,4178.668,2302.12,108.1835,''),
(20763,34,4180.668,2301.87,108.9335,''),
(20763,35,4182.668,2301.87,109.6835,''),
(20763,36,4184.418,2301.62,110.1835,''),
(20763,37,4187.418,2301.37,110.9335,''),
(20763,38,4189.418,2301.37,111.6835,''),
(20763,39,4191.418,2301.37,112.6835,''),
(20763,40,4193.418,2301.37,113.4335,''),
(20763,41,4195.418,2301.12,114.1835,''),
(20763,42,4172.752,2307.619,106.0487,''),
(20763,43,4174.502,2309.619,106.5487,''),
(20763,44,4176.752,2311.619,107.2987,''),
(20763,45,4175.089,2307.471,106.7038,''),
(20763,46,4177.089,2307.471,107.4538,''),
(20763,47,4178.839,2307.471,108.2038,''),
(20763,48,4180.839,2307.471,108.9538,''),
(20763,49,4182.839,2307.471,109.7038,''),
(20763,50,4178.212,2307.338,108.1149,''),
(20763,51,4180.212,2307.338,108.8649,''),
(20763,52,4181.962,2307.338,109.3649,''),
(20763,53,4183.962,2307.338,109.8649,''),
(20763,54,4185.962,2307.338,110.8649,''),
(20763,55,4195.536,2300.81,114.2211,''),
(20763,56,4196.286,2300.81,114.7211,''),
(20763,57,4198.286,2300.56,115.4711,''),
(20763,58,4201.036,2299.81,116.4711,''),
(20763,59,4203.036,2299.31,117.2211,''),
(20763,60,4205.036,2299.06,118.2211,''),
(20763,61,4207.036,2298.56,119.2211,''),
(20763,62,4208.786,2298.06,119.9711,''),
(20763,63,4210.786,2298.06,120.4711,''),
(20763,64,4212.536,2297.56,121.4711,''),
(20763,65,4214.536,2297.31,122.2211,''),
(20763,66,4217.536,2296.56,122.9711,''),
(20763,67,4219.536,2296.06,123.7211,''),
(20763,68,4221.536,2295.81,124.4711,''),
(20763,69,4205.864,2301.709,118.8695,''),
(20763,70,4207.864,2301.209,120.1195,''),
(20763,71,4208.864,2300.959,120.8695,''),
(20763,72,4211.614,2300.709,121.6195,''),
(20763,73,4221.648,2295.574,124.6826,''),
(20763,74,4223.398,2295.074,125.4326,''),
(20763,75,4225.398,2295.074,125.9326,''),
(20763,76,4227.398,2294.824,126.4326,''),
(20763,77,4229.398,2294.824,127.1826,''),
(20763,78,4232.398,2294.824,127.9326,''),
(20763,79,4234.148,2294.574,128.6826,''),
(20763,80,4237.148,2294.574,129.1826,''),
(20763,81,4242.148,2294.074,129.9326,''),
(20763,82,4221.031,2299.36,124.8262,''),
(20763,83,4224.031,2299.11,125.5762,''),
(20763,84,4226.031,2298.61,126.0762,''),
(20763,85,4227.781,2298.61,126.5762,''),
(20763,86,4229.781,2298.36,127.3262,''),
(20763,87,4231.781,2298.11,128.0762,''),
(20763,88,4229.808,2297.192,127.5853,''),
(20763,89,4233.058,2294.942,128.3353,''),
(20763,90,4234.558,2293.942,128.8353,''),
(20763,91,4237.808,2291.692,129.5853,''),
(20763,92,4246.382,2293.7,129.4793,''),
(20763,93,4251.382,2292.95,128.9793,''),
(20763,94,4255.132,2292.7,128.2293,''),
(20763,95,4256.882,2292.7,127.9793,''),
(20763,96,4259.882,2292.2,127.4793,''),
(20763,97,4263.808,2291.41,126.7324,''),
(20763,98,4264.058,2285.41,127.2324,''),
(20763,99,4264.058,2283.41,127.9824,''),
(20763,100,4264.058,2280.41,128.2324,''),
(20763,101,4264.058,2277.66,129.2324,''),
(20763,102,4264.058,2275.66,129.7324,''),
(20763,103,4264.308,2264.66,129.2324,''),
(20763,104,4264.47,2264.581,129.6417,''),
(20763,105,4264.47,2263.331,129.3917,''),
(20763,106,4262.72,2258.581,130.1417,''),
(20763,107,4261.72,2255.831,130.8917,''),
(20763,108,4260.97,2254.331,131.1417,''),
(20763,109,4259.72,2250.581,131.8917,''),
(20763,110,4258.97,2248.581,132.3917,''),
(20763,111,4258.47,2246.831,133.1417,''),
(20763,112,4258.137,2246.552,133.3581,''),
(20763,113,4257.637,2245.052,133.6081,''),
(20763,114,4256.637,2243.302,134.1081,''),
(20763,115,4254.887,2239.802,134.8581,''),
(20763,116,4252.887,2236.302,135.3581,''),
(20763,117,4251.137,2233.052,136.1081,''),
(20763,118,4249.887,2230.302,136.8581,''),
(20763,119,4247.887,2226.802,137.8581,''),
(20763,120,4246.13,2223.129,138.1115,''),
(20763,121,4250.954,2222.479,137.2872,''),
(20763,122,4249.704,2219.729,137.7872,''),
(20763,123,4248.578,2205.131,137.3916,''),
(20763,124,4250.209,2191.092,137.3059,''),
(20763,125,4251.209,2179.592,137.5559,'');
```

**Comment by Killyana** [comment]
There's too many extra wp, the script is good.

**Comment by Rushor** [comment]
yeah strange sniff output :(

**Comment by joschiwald** [comment]
you need only the end waypoint from each move update packet

**Comment by doktorblazen** [comment]
/FIXED WAYPOINTS/
Try it. It works for me :)

insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','1','4055','2293','113',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','2','4057','2301','112',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','3','4070','2302','111',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','4','4086','2296','109',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','5','4100','2298','107',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','6','4123','2294','104',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','7','4177','2303','107',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','8','4239','2292','129',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','9','4263','2291','126',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','10','4270','2284','125',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','11','4269','2264','127',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','12','4253','2235','135',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','13','4248','2213','137',NULL);
insert into waypoints (entry, pointid, position_x, position_y, position_z, point_comment) values('20763','14','4251','2172','137',NULL);

**Comment by illfated** [comment]
@doktorblazen : your SQL needs to look something like this in TC codestyle:
```sql
DELETE FROM `waypoints` WHERE `entry`=20763;
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
(20763,  1, 4055, 2293, 113, NULL),
(20763,  2, 4057, 2301, 112, NULL),
(20763,  3, 4070, 2302, 111, NULL),
(20763,  4, 4086, 2296, 109, NULL),
(20763,  5, 4100, 2298, 107, NULL),
(20763,  6, 4123, 2294, 104, NULL),
(20763,  7, 4177, 2303, 107, NULL),
(20763,  8, 4239, 2292, 129, NULL),
(20763,  9, 4263, 2291, 126, NULL),
(20763, 10, 4270, 2284, 125, NULL),
(20763, 11, 4269, 2264, 127, NULL),
(20763, 12, 4253, 2235, 135, NULL),
(20763, 13, 4248, 2213, 137, NULL),
(20763, 14, 4251, 2172, 137, NULL);
```
Please note that your coordinates look rounded off (manually adjusted) and do not look like sniffed values.

BTW, currently (in TrinityCore rev. 518e6299ca08 2019-01-19 17:41:03 +0100 (3.3.5 branch))
we have got this content:
```sql
SELECT * FROM `waypoints` WHERE `entry`=20763;
```
```
entry  pointid  position_x  position_y  position_z  point_comment
-----  -------  ----------  ----------  ----------  -------------
20763        1      4081.3      2296.6      110.75  (NULL)
20763        2      4095.3     2296.37     108.392  (NULL)
20763        3     4123.42     2297.51     104.368  (NULL)
20763        4     4146.48     2298.85     102.475  (NULL)
20763        5     4169.75     2301.11     104.503  (NULL)
20763        6     4181.37     2301.19     108.692  (NULL)
20763        7     4195.51     2301.28     113.981  (NULL)
20763        8     4215.69     2295.79     122.162  (NULL)
20763        9     4229.79     2295.09     127.068  (NULL)
20763       10     4250.86     2293.49     128.848  (NULL)
20763       11     4271.72        2290     125.243  (NULL)
20763       12     4277.21     2276.97     125.337  (NULL)
20763       13     4269.13     2262.97     127.868  (NULL)
20763       14     4262.07     2250.73     131.257  (NULL)
20763       15     4253.95     2236.66     134.959  (NULL)
20763       16     4249.61     2220.86     137.445  (NULL)
20763       17     4251.74     2186.12      137.08  (NULL)
20763       18        4252     2172.27     137.678  (NULL)
```
Have you tested on clean core & DB and found that it still does not work?
